// <auto-generated />
using EsempioEreditarietaFA;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EsempioEreditarietaFA.Migrations
{
    [DbContext(typeof(AziendaContext))]
    partial class AziendaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("EsempioEreditarietaFA.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Cognome")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Persona", (string)null);

                    b.HasDiscriminator<int>("Type").HasValue(0);
                });

            modelBuilder.Entity("EsempioEreditarietaFA.Dirigente", b =>
                {
                    b.HasBaseType("EsempioEreditarietaFA.Person");

                    b.Property<int>("NumeroDipendenti")
                        .HasColumnType("int");

                    b.Property<string>("Reporto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue(2);
                });

            modelBuilder.Entity("EsempioEreditarietaFA.Impiegato", b =>
                {
                    b.HasBaseType("EsempioEreditarietaFA.Person");

                    b.Property<int>("AnniServizio")
                        .HasColumnType("int");

                    b.Property<int>("Eta")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue(1);
                });
#pragma warning restore 612, 618
        }
    }
}
